# Generated by Django 5.2 on 2025-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trail_images/')),
                ('map_link', models.URLField(blank=True, null=True)),
                ('start_location', models.CharField(max_length=200)),
                ('ascent', models.IntegerField(help_text='Ascent in meters')),
                ('descent', models.IntegerField(help_text='Descent in meters')),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=5)),
                ('duration', models.DurationField(help_text='Expected duration (HH:MM)')),
                ('difficulty', models.CharField(max_length=100)),
                ('physical_requirements', models.TextField()),
            ],
        ),
    ]
