# Generated by Django 5.2 on 2025-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
