# Generated by Django 5.2 on 2025-04-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trail_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trails.trail')),
            ],
        ),
    ]
