# Generated by Django 5.2 on 2025-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_alter_trail_ascent_alter_trail_descent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='ascent',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='descent',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='physical_requirements',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='start_location',
        ),
        migrations.AddField(
            model_name='trail',
            name='latitude',
            field=models.FloatField(default=46.8, help_text='Latitude of the trail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='longitude',
            field=models.FloatField(default=6.9, help_text='Longitude of the trail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.CharField(help_text='e.g. 14.5', max_length=20),
        ),
    ]
