# Generated by Django 5.2 on 2025-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_remove_trail_ascent_remove_trail_descent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='map_link',
        ),
        migrations.AddField(
            model_name='trail',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Paste only the iframe src URL', null=True),
        ),
    ]
