# Generated by Django 5.2 on 2025-04-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_remove_trail_map_link_trail_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='canton',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trail_images/'),
        ),
    ]
