# Generated by Django 5.2 on 2025-04-24 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_trail_canton_trail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trails.trail')),
            ],
        ),
    ]
