# Generated by Django 5.2 on 2025-04-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
