# Generated by Django 5.1.5 on 2025-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_rename_content_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Paste only the URL', null=True),
        ),
    ]
